### ISSUE TITLE
[PE-D][Tester D] Text covered by ChildrenList text

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-2/tp#222] opened 2023-11-03 19:08 UTC
I'm not able to see Ben's email address due to the `~/grp-002/>'s Children List` UI text. 
![Screenshot 2023-11-03 at 4.27.57 PM.png](https://raw.githubusercontent.com/jianyangg/ped/main/files/89dfbbaf-8ab3-4529-a276-bd833faf9f88.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jianyangg/ped#1

**Comment by NereusWB922** [comment] 2023-11-04 04:54
This issue is a duplicate of #237  Closing.

**Closed by NereusWB922** 2023-11-04 04:54 UTC
